services:
  - type: web
    name: ecocom-yolo-api
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      uvicorn app:app --host 0.0.0.0 --port $PORT
